### ISSUE TITLE
Explain what DSL is the first time you mention it 

### ISSUE THREAD

**Issue by stefania11** [learn-co-curriculum/rake-todo#21]
I tried to edit this directly but edit function does't work for me.

**Comment by AnnJohn** [comment]
@stefania11 Hi Stefania. In an effort to get more clearer issues raised, could you be  a little more specific   regarding this issue.

In what file and which lines is the issue? (Screenshots are always helpful)
What were you expecting, and what did you see?
If you have a suggested solution, please feel free to include. 

Thanks

**Comment by stefania11** [comment]
It's on readme file line 21. I referenced it in the subject of issue but
maybe not clear enough.


Stefania Druga - Founder

+1 415 503 89 44

-----------------------------------------------------------------------------


HacKIDemia: Inspire the kids to imagine a better tomorrow

and give them the tools to build it!



Web <http://www.hackidemia.com/>| Facebook
<https://www.facebook.com/Hackidemia>| Twitter
<https://twitter.com/HacKidemia>| YouTube
<http://www.youtube.com/user/HacKIDemia>| Newsletter <http://bit.ly/ZrvxtF>|

**Comment by AnnJohn** [comment]
Iceboxing for now
